name: Java CI with Gradle

# 동작 조건 설정 : main 브랜치에 push 혹은 pull request가 발생할 경우 동작한다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # gradlew 파일에 실행 권한을 부여하는 작업 추가
    - name: Grant execute permission to gradlew
      run: chmod +x gradlew
      working-directory: ${{ github.workspace }}

    - name: make application.properties
      run: |
        mkdir -p src/main/resources
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.application_properties }}" > ./application.properties
      shell: bash
     
    # 6. 다른 argoCD 전용 리포지토리에 매니페스트 파일 업데이트
    - name: Update Manifest in argoCD Repository
      run: |
        git clone https://leeinhong9512:${{ secrets.LOGIN_GITHUB_TOKEN }}@github.com/KCS-final/backend-argocd.git
        cd backend-argocd
        sed -i 's|image: leeinhong9512/panda-backend:.*|image: leeinhong9512/panda-backend:${{ github.sha }}|' backend.yaml
        git config --global user.name InhongLee95
        git config --global user.email leeinhong9512@gmail.com
        git add backend.yaml
        git commit -m "Update image tag to latest"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.LOGIN_GITHUB_TOKEN }}
